FROM ubuntu

MAINTAINER Diah Anggraeni Pitaloka

RUN apt-get update \
	&& apt-get install imagemagick \
	parallel
	
RUN apt-get install \python-numpy
	python-pandas 
	
	

--file that have to be installed

1. sudo pip install pandas
2. sudo apt-get update
3. sudo apt-get install python-pandas
4. sudo apt-get install parallel
5. sudo apt-get install imagemagick

sudo docker ps –a # Get list of all containers previously started with run command
sudo docker commit container_id image_name 

container : 30f893be6eb9
sha256:8b852caaafbb9a78cf76d4f3a33fa4a12b0bfa2d5ae2d0ce5d75d056bb9d6f87
image gcr.io/tensorflow/tensorflow:latest-devel-gpu

last docker commit
container id : 30f893be6eb9 
image   : 69b6e3b784df
sha256:289fae5d763959c92cf4395b7735cf3a4b198281412b9d9fe1edd152588d5643


nvidia-docker run -it -p 8888:8888 -v /mnt/5854F7AC54F78B50/dataset/dm_challenge/:/dm_challenge gcr.io/tensorflow/tensorflow:latest-devel-gpu /bin/bash


docker run -i -t -v /mnt/5854F7AC54F78B50/dataset/dm_challenge/:/dm_challenge 69b6e3b784df /bin/bash

docker tag 69b6e3b784df diahpitaloka15/dm-preprocess:latest
